name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2

    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "pnpm"

    - uses: oven-sh/setup-bun@v1

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install
